### ISSUE TITLE
ST2 cannot seem to read Pandoc.sublime-settings

### ISSUE THREAD

**Issue by wcrissman** [tbfisher/sublimetext-Pandoc#27]
I'm using ST2 and manually obtained the 1.x branch with the following:

```bash
cd ~/Library/Application\ Support/Sublime\ Text\ 2/Packages
git clone -b 1.x https://github.com/tbfisher/sublimetext-Pandoc
```
Then restarted ST2.

Verified by viewing the readme `# Pandoc Plugin for Sublime Text 2`

My user settings file looks like the following:
```json
{
    "user": {
        "pandoc-path": "/usr/local/bin/pandoc"
    }
}
```

When I try to execute pandoc through the Command Pallete to convert orgmode to markdown, plaintext, anything, the console shows:
```
Traceback (most recent call last):
  File "./Pandoc.py", line 53, in transform
  File "./Pandoc.py", line 138, in _src_format
  File "./Pandoc.py", line 155, in _format_conf
KeyError: None
```

When I try to view the default package settings, the console shows:
```
Unable to open ~/Library/Application Support/Sublime Text 2/Packages/Pandoc/Pandoc.sublime-settings
```

I tried to work around this by adding the settings found in the defaults file to the user file, but I am getting the same stack trace in the console.

**Comment by MPvHarmelen** [comment]
Do you still have this issue?
