### ISSUE TITLE
rst to pdf only st2 ,not st3 ?

### ISSUE THREAD

**Issue by midui** [tbfisher/sublimetext-Pandoc#61]
I get the following error when trying to Render rst to pdf. I have already configured the tool and my pandoc path is :

```
"pandoc-path": "C:/Users/P70/AppData/Local/Pandoc/pandoc.exe"

"PDF": {
        "scope": {
          "text.html": "html",
          "text.html.markdown": "markdown"
        },
        "pandoc-arguments": [
          "-t", "pdf",
          "--latex-engine=xelatex",
         "--template=pm-template.latex"
        ]
      },

```
Fail to generate output.
_
> error: No transformations configured for the syntax Packages/RestructuredText/reStructuredText.sublime-syntax
> Traceback (most recent call last):
>   File "D:\md\Sublime Text Build 3126 x64\sublime_plugin.py", line 797, in run_
>     return self.run()
>   File "Pandoc in D:\md\Sublime Text Build 3126 x64\Data\Installed Packages\Pandoc.sublime-package", line 46, in run
>   File "D:\md\Sublime Text Build 3126 x64\sublime.py", line 448, in show_quick_panel
>     if len(items) > 0 and isinstance(items[0], list):
> TypeError: object of type 'NoneType' has no len()

_

But, I do rst to pdf is successful with pandoc st2!

 Assistance appreciated.
 
Platform:
Window 10
sublime 3

**Comment by MPvHarmelen** [comment]
This plugin has different versions for ST2 and 3. Do you still have this problem?
