### ISSUE TITLE
Error outputting HTML 5 after 467e8ae

### ISSUE THREAD

**Issue by bryanlammon** [tbfisher/sublimetext-Pandoc#82]
The recent update (467e8ae) broke HTML 5 output for me. When I invoke the Pandoc command and select HTML 5, I get the following error in the console:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1488, in run_
    return self.run(edit, **args)
  File "/Users/[username]/Library/Application Support/Sublime Text/Packages/Pandoc/Pandoc.py", line 165, in run
    if oformat is not None and oformat in _s('pandoc-format-file'):
  File "/Users/[username]/Library/Application Support/Sublime Text/Packages/Pandoc/Pandoc.py", line 275, in _s
    return merge_user_settings()[key]
KeyError: 'pandoc-format-file'
```

Manually installing the plugin, setting `ignore_vcs_packages` to `true`, and reverting to the previous commit (6c099a2) solved the issue.

**Comment by workergnome** [comment]
Confirming I'm seeing similar issues when trying to convert to PDF after the update.  

Also, the default settings appear to be completely missing.

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1488, in run_
    return self.run(edit, **args)
  File "/Users/[username]/Library/Application Support/Sublime Text 3/Installed Packages/Pandoc.sublime-package/Pandoc.py", line 165, in run
  File "/Users/[username]/Library/Application Support/Sublime Text 3/Installed Packages/Pandoc.sublime-package/Pandoc.py", line 275, in _s
KeyError: 'pandoc-format-file'
```

![Screenshot 2023-05-30 at 7 07 28 PM](https://github.com/tbfisher/sublimetext-Pandoc/assets/34536/5a79ed38-ce30-4288-8bc7-7d49b649b7ea)

**Comment by MPvHarmelen** [comment]
Thanks! I don't know why I didn't notice that file rename before accepting the other pull request :thinking:  It should be fixed now!
